name: First workflow
on: workflow_dispatch
jobs:
  first-run:
    runs-on: ubuntu-slim
    steps:
      - run: echo "hello"
        name: Greet
      - run: |
          echo "running step 1"
          echo "running step 2"
      - name: bye
        run: echo "bye"  
